CityFragment.java:92: выдает:
CityFragment.java:92: error: incomparable types: String and int
if (detailsFragment == null || currentCity.getCityName() != detailsFragment.getCurrentCity().getImageMonuments()) { //??
указывая стрелкой ^ на ( !=)

CityFragment.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.

CoatFragment.java:47 выдает:

CoatFragment.java:47: error: method getResourceId in class TypedArray cannot be applied to given types;
coatCity.setImageResource(imgs.getResourceId(city.getImageMonuments() -1)); // ??
^
required: int,int
found: int
reason: actual and formal argument lists differ in length.

--

если закоментить эти пока что строчки приложение запускается но когда я выбираю город он открывает фрагмент нужный город - он его переносит что да это москва например но картинка всегда соответствует одной не меняется взависимости от города.